Config = {}

Config.OnlyDriver = true

Config.Speedlimits = {
	["AIRP"] = 10, -- Los Santos International Airport
	["ALAMO"] = 20, -- Alamo Sea
	["ALTA"] = 30, -- Alta
	["ARMYB"] = 40, -- Fort Zancudo
	["BANHAMC"] = 50, -- Banham Canyon Dr
	["BANNING"] = 60, -- Banning
	["BEACH"] = 70, -- Vespucci Beach
	["BHAMCA"] = 80, -- Banham Canyon
	["BRADP"] = 90, -- Braddock Pass
	["BRADT"] = 80, -- Braddock Tunnel
	["BURTON"] = 70, -- Burton
	["CALAFB"] = 60, -- Calafia Bridge
	["CANNY"] = 50, -- Raton Canyon
	["CCREAK"] = 40, -- Cassidy Creek
	["CHAMH"] = 30, -- Chamberlain Hills
	["CHIL"] = 20, -- Vinewood Hills
	["CHU"] = 10, -- Chumash
	["CMSW"] = 20, -- Chiliad Mountain State Wilderness
	["CYPRE"] = 30, -- Cypress Flats
	["DAVIS"] = 40, -- Davis
	["DELBE"] = 50, -- Del Perro Beach
	["DELPE"] = 60, -- Del Perro
	["DELSOL"] = 70, -- La Puerta
	["DESRT"] = 80, -- Grand Senora Desert
	["DOWNT"] = 90, -- Downtown
	["DTVINE"] = 80, -- Downtown Vinewood
	["EAST_V"] = 70, -- East Vinewood
	["EBURO"] = 60, -- El Burro Heights
	["ELGORL"] = 50, -- El Gordo Lighthouse
	["ELYSIAN"] = 40, -- Elysian Island
	["GALFISH"] = 30, -- Galilee
	["GOLF"] = 20, -- GWC and Golfing Society
	["GRAPES"] = 10, -- Grapeseed
	["GREATC"] = 20, -- Great Chaparral
	["HARM"] = 30, -- Harmony
	["HAWICK"] = 40, -- Hawick
	["HORS"] = 50, -- Vinewood Racetrack
	["HUMLAB"] = 60, -- Humane Labs and Research
	["JAIL"] = 70, -- Bolingbroke Penitentiary
	["KOREAT"] = 80, -- Little Seoul
	["LACT"] = 90, -- Land Act Reservoir
	["LAGO"] = 80, -- Lago Zancudo
	["LDAM"] = 70, -- Land Act Dam
	["LEGSQU"] = 60, -- Legion Square
	["LMESA"] = 50, -- La Mesa
	["LOSPUER"] = 40, -- La Puerta
	["MIRR"] = 30, -- Mirror Park
	["MORN"] = 20, -- Morningwood
	["MOVIE"] = 10, -- Richards Majestic
	["MTCHIL"] = 20, -- Mount Chiliad
	["MTGORDO"] = 30, -- Mount Gordo
	["MTJOSE"] = 40, -- Mount Josiah
	["MURRI"] = 50, -- Murrieta Heights
	["NCHU"] = 60, -- North Chumash
	["NOOSE"] = 70, -- N.O.O.S.E
	["OCEANA"] = 80, -- Pacific Ocean
	["PALCOV"] = 90, -- Paleto Cove
	["PALETO"] = 80, -- Paleto Bay
	["PALFOR"] = 70, -- Paleto Forest
	["PALHIGH"] = 60, -- Palomino Highlands
	["PALMPOW"] = 50, -- Palmer-Taylor Power Station
	["PBLUFF"] = 40, -- Pacific Bluffs
	["PBOX"] = 30, -- Pillbox Hill
	["PROCOB"] = 20, -- Procopio Beach
	["RANCHO"] = 10, -- Rancho
	["RGLEN"] = 20, -- Richman Glen
	["RICHM"] = 30, -- Richman
	["ROCKF"] = 40, -- Rockford Hills
	["RTRAK"] = 50, -- Redwood Lights Track
	["SANAND"] = 60, -- San Andreas
	["SANCHIA"] = 70, -- San Chianski Mountain Range
	["SANDY"] = 80, -- Sandy Shores
	["SKID"] = 90, -- Mission Row
	["SLAB"] = 80, -- Stab City
	["STAD"] = 70, -- Maze Bank Arena
	["STRAW"] = 60, -- Strawberry
	["TATAMO"] = 50, -- Tataviam Mountains
	["TERMINA"] = 40, -- Terminal
	["TEXTI"] = 30, -- Textile City
	["TONGVAH"] = 20, -- Tongva Hills
	["TONGVAV"] = 10, -- Tongva Valley
	["VCANA"] = 20, -- Vespucci Canals
	["VESP"] = 30, -- Vespucci
	["VINE"] = 40, -- Vinewood
	["WINDF"] = 50, -- Ron Alternates Wind Farm
	["WVINE"] = 60, -- West Vinewood
	["ZANCUDO"] = 70, -- Zancudo River
	["ZP_ORT"] = 80, -- Port of South Los Santos
	["ZQ_UAR"] = 90, -- Davis Quartz
	["PROL"] = 80, -- Prologue / North Yankton
	["ISHeist"] = 70 -- Cayo Perico Island
}
